// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStore;

namespace SportsStore.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsStore.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Name = "Product 1",
                            Price = 21m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            Name = "Product 2",
                            Price = 22m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            Name = "Product 3",
                            Price = 23m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 5,
                            Name = "Product 4",
                            Price = 24m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Name = "Product 5",
                            Price = 25m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Name = "Product 6",
                            Price = 26m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Name = "Product 7",
                            Price = 27m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            Name = "Product 8",
                            Price = 28m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Name = "Product 9",
                            Price = 29m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Name = "Product 10",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            Name = "Product 11",
                            Price = 31m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Name = "Product 12",
                            Price = 32m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            Name = "Product 13",
                            Price = 33m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            Name = "Product 14",
                            Price = 34m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            Name = "Product 15",
                            Price = 35m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 5,
                            Name = "Product 16",
                            Price = 36m
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5,
                            Name = "Product 17",
                            Price = 37m
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4,
                            Name = "Product 18",
                            Price = 38m
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1,
                            Name = "Product 19",
                            Price = 39m
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            Name = "Product 20",
                            Price = 40m
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            Name = "Product 21",
                            Price = 41m
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 4,
                            Name = "Product 22",
                            Price = 42m
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 5,
                            Name = "Product 23",
                            Price = 43m
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 3,
                            Name = "Product 24",
                            Price = 44m
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3,
                            Name = "Product 25",
                            Price = 45m
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 1,
                            Name = "Product 26",
                            Price = 46m
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 2,
                            Name = "Product 27",
                            Price = 47m
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 5,
                            Name = "Product 28",
                            Price = 48m
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 1,
                            Name = "Product 29",
                            Price = 49m
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 2,
                            Name = "Product 30",
                            Price = 50m
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 1,
                            Name = "Product 31",
                            Price = 51m
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 5,
                            Name = "Product 32",
                            Price = 52m
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 5,
                            Name = "Product 33",
                            Price = 53m
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 1,
                            Name = "Product 34",
                            Price = 54m
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 4,
                            Name = "Product 35",
                            Price = 55m
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 5,
                            Name = "Product 36",
                            Price = 56m
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 2,
                            Name = "Product 37",
                            Price = 57m
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 2,
                            Name = "Product 38",
                            Price = 58m
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 1,
                            Name = "Product 39",
                            Price = 59m
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 3,
                            Name = "Product 40",
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 5,
                            Name = "Product 41",
                            Price = 61m
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 5,
                            Name = "Product 42",
                            Price = 62m
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 2,
                            Name = "Product 43",
                            Price = 63m
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 3,
                            Name = "Product 44",
                            Price = 64m
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 5,
                            Name = "Product 45",
                            Price = 65m
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 3,
                            Name = "Product 46",
                            Price = 66m
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 3,
                            Name = "Product 47",
                            Price = 67m
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 4,
                            Name = "Product 48",
                            Price = 68m
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 1,
                            Name = "Product 49",
                            Price = 69m
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 3,
                            Name = "Product 50",
                            Price = 70m
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 3,
                            Name = "Product 51",
                            Price = 71m
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 1,
                            Name = "Product 52",
                            Price = 72m
                        },
                        new
                        {
                            ProductId = 53,
                            CategoryId = 5,
                            Name = "Product 53",
                            Price = 73m
                        },
                        new
                        {
                            ProductId = 54,
                            CategoryId = 3,
                            Name = "Product 54",
                            Price = 74m
                        },
                        new
                        {
                            ProductId = 55,
                            CategoryId = 4,
                            Name = "Product 55",
                            Price = 75m
                        },
                        new
                        {
                            ProductId = 56,
                            CategoryId = 3,
                            Name = "Product 56",
                            Price = 76m
                        },
                        new
                        {
                            ProductId = 57,
                            CategoryId = 3,
                            Name = "Product 57",
                            Price = 77m
                        },
                        new
                        {
                            ProductId = 58,
                            CategoryId = 2,
                            Name = "Product 58",
                            Price = 78m
                        },
                        new
                        {
                            ProductId = 59,
                            CategoryId = 2,
                            Name = "Product 59",
                            Price = 79m
                        },
                        new
                        {
                            ProductId = 60,
                            CategoryId = 2,
                            Name = "Product 60",
                            Price = 80m
                        },
                        new
                        {
                            ProductId = 61,
                            CategoryId = 1,
                            Name = "Product 61",
                            Price = 81m
                        },
                        new
                        {
                            ProductId = 62,
                            CategoryId = 2,
                            Name = "Product 62",
                            Price = 82m
                        },
                        new
                        {
                            ProductId = 63,
                            CategoryId = 4,
                            Name = "Product 63",
                            Price = 83m
                        },
                        new
                        {
                            ProductId = 64,
                            CategoryId = 1,
                            Name = "Product 64",
                            Price = 84m
                        },
                        new
                        {
                            ProductId = 65,
                            CategoryId = 5,
                            Name = "Product 65",
                            Price = 85m
                        },
                        new
                        {
                            ProductId = 66,
                            CategoryId = 5,
                            Name = "Product 66",
                            Price = 86m
                        },
                        new
                        {
                            ProductId = 67,
                            CategoryId = 2,
                            Name = "Product 67",
                            Price = 87m
                        },
                        new
                        {
                            ProductId = 68,
                            CategoryId = 4,
                            Name = "Product 68",
                            Price = 88m
                        },
                        new
                        {
                            ProductId = 69,
                            CategoryId = 1,
                            Name = "Product 69",
                            Price = 89m
                        },
                        new
                        {
                            ProductId = 70,
                            CategoryId = 2,
                            Name = "Product 70",
                            Price = 90m
                        },
                        new
                        {
                            ProductId = 71,
                            CategoryId = 3,
                            Name = "Product 71",
                            Price = 91m
                        },
                        new
                        {
                            ProductId = 72,
                            CategoryId = 4,
                            Name = "Product 72",
                            Price = 92m
                        },
                        new
                        {
                            ProductId = 73,
                            CategoryId = 3,
                            Name = "Product 73",
                            Price = 93m
                        },
                        new
                        {
                            ProductId = 74,
                            CategoryId = 3,
                            Name = "Product 74",
                            Price = 94m
                        },
                        new
                        {
                            ProductId = 75,
                            CategoryId = 4,
                            Name = "Product 75",
                            Price = 95m
                        },
                        new
                        {
                            ProductId = 76,
                            CategoryId = 3,
                            Name = "Product 76",
                            Price = 96m
                        },
                        new
                        {
                            ProductId = 77,
                            CategoryId = 2,
                            Name = "Product 77",
                            Price = 97m
                        },
                        new
                        {
                            ProductId = 78,
                            CategoryId = 3,
                            Name = "Product 78",
                            Price = 98m
                        },
                        new
                        {
                            ProductId = 79,
                            CategoryId = 3,
                            Name = "Product 79",
                            Price = 99m
                        },
                        new
                        {
                            ProductId = 80,
                            CategoryId = 5,
                            Name = "Product 80",
                            Price = 100m
                        },
                        new
                        {
                            ProductId = 81,
                            CategoryId = 3,
                            Name = "Product 81",
                            Price = 101m
                        },
                        new
                        {
                            ProductId = 82,
                            CategoryId = 3,
                            Name = "Product 82",
                            Price = 102m
                        },
                        new
                        {
                            ProductId = 83,
                            CategoryId = 4,
                            Name = "Product 83",
                            Price = 103m
                        },
                        new
                        {
                            ProductId = 84,
                            CategoryId = 3,
                            Name = "Product 84",
                            Price = 104m
                        },
                        new
                        {
                            ProductId = 85,
                            CategoryId = 5,
                            Name = "Product 85",
                            Price = 105m
                        },
                        new
                        {
                            ProductId = 86,
                            CategoryId = 5,
                            Name = "Product 86",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 87,
                            CategoryId = 1,
                            Name = "Product 87",
                            Price = 107m
                        },
                        new
                        {
                            ProductId = 88,
                            CategoryId = 2,
                            Name = "Product 88",
                            Price = 108m
                        },
                        new
                        {
                            ProductId = 89,
                            CategoryId = 2,
                            Name = "Product 89",
                            Price = 109m
                        },
                        new
                        {
                            ProductId = 90,
                            CategoryId = 2,
                            Name = "Product 90",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 91,
                            CategoryId = 3,
                            Name = "Product 91",
                            Price = 111m
                        },
                        new
                        {
                            ProductId = 92,
                            CategoryId = 1,
                            Name = "Product 92",
                            Price = 112m
                        },
                        new
                        {
                            ProductId = 93,
                            CategoryId = 5,
                            Name = "Product 93",
                            Price = 113m
                        },
                        new
                        {
                            ProductId = 94,
                            CategoryId = 5,
                            Name = "Product 94",
                            Price = 114m
                        },
                        new
                        {
                            ProductId = 95,
                            CategoryId = 3,
                            Name = "Product 95",
                            Price = 115m
                        },
                        new
                        {
                            ProductId = 96,
                            CategoryId = 3,
                            Name = "Product 96",
                            Price = 116m
                        },
                        new
                        {
                            ProductId = 97,
                            CategoryId = 2,
                            Name = "Product 97",
                            Price = 117m
                        },
                        new
                        {
                            ProductId = 98,
                            CategoryId = 2,
                            Name = "Product 98",
                            Price = 118m
                        },
                        new
                        {
                            ProductId = 99,
                            CategoryId = 3,
                            Name = "Product 99",
                            Price = 119m
                        },
                        new
                        {
                            ProductId = 100,
                            CategoryId = 1,
                            Name = "Product 100",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("SportsStore.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("productCategories");
                });

            modelBuilder.Entity("SportsStore.ProductPicture", b =>
                {
                    b.Property<int>("ProductPictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PictureLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductPictureId");

                    b.HasIndex("ProductId");

                    b.ToTable("productPictures");

                    b.HasData(
                        new
                        {
                            ProductPictureId = 1,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 2,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 3,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 4,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 5,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 6,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 7,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 8,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 9,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 10,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 11,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 12,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 13,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 14,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 15,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 16,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 17,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 18,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 19,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 20,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 21,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 22,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 23,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 24,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 25,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 26,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 27,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 28,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 29,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 30,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 31,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 32,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 33,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 34,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 35,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 36,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 37,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 38,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 39,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 40,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 41,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 42,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 43,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 44,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 45,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 46,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 47,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 48,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 49,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 50,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 51,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 52,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 53,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 54,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 55,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 56,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 57,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 58,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 59,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 60,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 61,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 62,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 63,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 64,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 65,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 66,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 67,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 68,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 69,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 70,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 71,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 72,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 73,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 74,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 75,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 76,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 77,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 78,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 79,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 80,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 81,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 82,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 83,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 84,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 85,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 86,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 87,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 88,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 89,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 90,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 91,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 92,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 93,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 94,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 95,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 96,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 97,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 98,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 99,
                            PictureLocation = "https://via.placeholder.com/150"
                        },
                        new
                        {
                            ProductPictureId = 100,
                            PictureLocation = "https://via.placeholder.com/150"
                        });
                });

            modelBuilder.Entity("SportsStore.Product", b =>
                {
                    b.HasOne("SportsStore.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");
                });

            modelBuilder.Entity("SportsStore.ProductPicture", b =>
                {
                    b.HasOne("SportsStore.Product", null)
                        .WithMany("ProductPicuture")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
